---
- hosts: all
  become: true
  tasks:
    - name: setup pgdg
      package:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
    - name: disable postgres modules
      shell: dnf -yq module disable postgresql

    - name: install postgres
      package:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql12
        - postgresql12-server
        - postgresql12-llvmjit

    - name: check if data dir exists
      shell: /usr/pgsql-12/bin/postgresql-12-check-db-dir /var/lib/pgsql/12/data
      register: datadir_check
      ignore_errors: true

    - name: create postgres data dir
      shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
      when: datadir_check.rc != 0

    - name: start postgres
      systemd:
        name: postgresql-12
        state: started

    - name: install vim
      package:
        name: vim
        state: present
